PlanItURL=http://jupiter.cloud.planittesting.com
ContactPage=https://jupiter.cloud.planittesting.com/#/contact
RandomEmail=manoj@test.com
Forename=Manoj
Message=Testing by Manoj
Item_1=Stuffed Frog
Item_2=Fluffy Bunny
Item_3=Valentine Bear